[Interface]
Address = 10.200.0.2/32
ListenPort = 51820
PrivateKey = PrivateKey_Francoforte_for_Raspberry

#Abilito l'inoltro e il mascheramento sull'interfaccia pubblica del server di Francoforte
PostUp = ufw route allow in on wg_h_fr out on eth0
PostUp = iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostUp = ufw route allow in on eth0 out on wg_h_fr

#Rimozione in PreDown
PreDown = ufw route delete allow in on wg_h_fr out on eth0 || true
PreDown = ufw route delete allow in on eth0 out on wg_h_fr || true
PreDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE || true

[Peer]
PublicKey = PublicKey_Raspberry_for_Francoforte
AllowedIPs = 10.200.0.1/32
Endpoint = 93.49.92.81:51820

[Peer]
PublicKey = PublicKey_Device2
AllowedIPs = 10.200.0.3/32

[Peer]
PublicKey = PublicKey_Device3
AllowedIPs = 10.200.0.4/32
