[Interface]
Address = 10.50.0.1/24
PrivateKey = PrivateKey_Raspberry_to_Home
ListenPort = 51825

PostUp = iptables -A FORWARD -i wgB -j ACCEPT
PostUp = iptables -A FORWARD -o wgB -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -o eth0 -s 10.50.0.0/24 -j MASQUERADE

PostUp = iptables -A INPUT -i wgB -p tcp --dport 22 -j ACCEPT #Per accedere tramite ssh
PostUp = iptables -A INPUT -i wgB -p icmp -j ACCEPT #Per testare il ping

#Marco i pacchetti in uscita
PostUp = iptables -t mangle -A OUTPUT -p udp --sport 51825 -j MARK --set-mark 0xca71
PostUp = iptables -t mangle -A OUTPUT -s 10.50.0.0/24 -j MARK --set-mark 0xca71

#Aggiungo la regola di routing sulla tabella phone creata in rt_tables
PostUp = ip rule add fwmark 0xca71 table phone priority 100
PostUp = ip route add default via 192.168.3.1 dev eth0 table phone

#Rimozione in PreDown
PreDown = iptables -D FORWARD -i wgB -j ACCEPT || true
PreDown = iptables -D FORWARD -o wgB -j ACCEPT || true
PreDown = iptables -t nat -D POSTROUTING -o eth0 -s 10.50.0.0/24 -j MASQUERADE || true

PreDown = iptables -t mangle -D OUTPUT -p udp --sport 51825 -j MARK --set-mark 0xca71 || true
PreDown = iptables -t mangle -D OUTPUT -s 10.50.0.0/24 -j MARK --set-mark 0xca71 || true

PreDown = ip rule del fwmark 0xca71 table phone priority 100 || true
PreDown = ip route del default via 192.168.3.1 dev eth0 table phone || true

[Peer]
PublicKey = PublicKey_Device1
AllowedIPs = 10.50.0.2/32

[Peer]
PublicKey = PublicKey_Device2
AllowedIPs = 10.50.0.3/32

[Peer]
PublicKey = PublicKey_Device3
AllowedIPs = 10.50.0.4/32
